from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.maximize_window()
driver.get('https://www.redbus.in/')
time.sleep(4)
driver.find_element_by_xpath("//input[@id='src']").click()
driver.find_element_by_xpath("//input[@id='src']").send_keys('Anantapur (andhra pradesh)')
time.sleep(4)
driver.find_element_by_xpath("//input[@id='dest']").click()
driver.find_element_by_xpath("//input[@id='dest']").send_keys('Nellore')
time.sleep(3)
driver.find_element_by_xpath("//input[@id='onward_cal']").click()
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[4]/table/tbody/tr[6]/td[3]').click()
driver.find_element_by_xpath("//button[@id='search_btn']").click()
time.sleep(3)
driver.back()
time.sleep(3)
driver.forward()
#driver.switch_to_alert
driver.find_element_by_xpath("//div[@id='select_box_sign']").click()
time.sleep(3)
driver.find_element_by_xpath('/html/body/section/header/div/div/div[2]/div[1]/div/div/div[2]/div/ul/li')
