from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.maximize_window()
driver.get('https://www.flipkart.com/')
time.sleep(3)
driver.find_element_by_xpath("//button[@class='_2KpZ6l _2doB4z']").click()
time.sleep(2)
driver.find_element_by_xpath("//a[text()='Login']").click()
time.sleep(2)
driver.find_element_by_xpath('/html/body/div[2]/div/div/div/div/div[2]/div/form/div[1]/input').send_keys('7396405570')
time.sleep(3)
driver.find_element_by_xpath("//input[@type='password']").send_keys('Pavankalyan#$12')
time.sleep(3)
driver.find_element_by_xpath("//button[@class='_2KpZ6l _2HKlqd _3AWRsL']").click()
time.sleep(3)
driver.find_element_by_name('q').send_keys('mens t shirts')
driver.find_element_by_xpath("//button[@type='submit']").click()
time.sleep(2)
driver.find_element_by_xpath("//div[@class='_24_Dny']").click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="container"]/div/div[3]/div/div[2]/div[4]/div/div[3]/div/a/div[1]/div/div/div/img').click()
time.sleep(3)
driver.execute_script('window.scrollTo(0,1000)')
driver.save_screenshot(r"C:\Users\91630\PycharmProjects\niklaus1\pn.png")
driver.forward()
time.sleep(3)
driver.find_element_by_xpath("//*[text()='BUY NOW']").click()